Feat - simplify send flow
bithyve/bitcoin-tribe pull request #651
Opened 2024-12-30 11:51 UTC by akshay8551

#460

Note - Light mode is not receive yet, so implementation is pending.

2025-01-03 12:04 UTC, cakesoft-shashank commented on src/screens/send/components/SendToContainer.tsx
> +              getFeeRateByPriority={getFeeRateByPriority(TxPriority.LOW)}
Raname the prop name here. Its a value not function so don't use get

2025-01-03 12:28 UTC, cakesoft-shashank requested changes

2025-01-03 12:28 UTC, cakesoft-shashank commented on src/components/CurrencySwitch.tsx
> +  currentCurrencyMode: string;
Use proper type here

2025-01-03 12:28 UTC, cakesoft-shashank commented on src/components/CurrencySwitch.tsx
> +  // useEffect(() => {
Remove this

2025-01-03 12:29 UTC, cakesoft-shashank requested changes
Remove comments and console logs

2025-01-03 12:56 UTC, akshay8551 commented on src/screens/send/components/SendToContainer.tsx
> +              getFeeRateByPriority={getFeeRateByPriority(TxPriority.LOW)}
resolved

2025-01-03 12:56 UTC, akshay8551 commented on src/components/CurrencySwitch.tsx
> +  currentCurrencyMode: string;
Resolved

2025-01-03 12:56 UTC, akshay8551 commented on src/components/CurrencySwitch.tsx
> +  // useEffect(() => {
Removed

2025-01-03 16:35 UTC, cakesoft-shashank reviewed
Swipe action and fee selection need to add in asset send screen(onchain and LN)

2025-01-03 16:35 UTC, cakesoft-shashank commented on src/screens/send/components/SendToContainer.tsx
>                getEstimatedBlocksByPriority={getEstimatedBlocksByPriority(
this is remaining

2025-01-03 16:50 UTC, akshay8551 commented on src/screens/send/components/SendToContainer.tsx
>                getEstimatedBlocksByPriority={getEstimatedBlocksByPriority(
Renamed props name (removed `get`) please have check..

2025-01-03 17:07 UTC, akshay8551 commented on src/screens/send/components/SendToContainer.tsx
>                getEstimatedBlocksByPriority={getEstimatedBlocksByPriority(
Resolved.

2025-01-06 08:17 UTC, cakesoft-shashank approved these changes

2025-01-06 08:17 UTC, merged